CREATE TABLE DEVELOPER (NAME VARCHAR(255) NOT NULL, PRIMARY KEY (NAME));
CREATE TABLE ISSUE (ISSUE_ID BIGINT NOT NULL, type VARCHAR(31), CREATION_DATE TIMESTAMP, DESCRIPTION VARCHAR(255), DEVELOPER_NAME VARCHAR(255), TITLE VARCHAR(255), PRIMARY KEY (ISSUE_ID));
CREATE TABLE BUG (ISSUE_ID BIGINT NOT NULL, BUG_STATUS VARCHAR(255), PRIORITY VARCHAR(255), PRIMARY KEY (ISSUE_ID));
CREATE TABLE STORY (ISSUE_ID BIGINT NOT NULL, ESTIMATED_POINTS BIGINT, STORY_STATUS VARCHAR(255), PRIMARY KEY (ISSUE_ID));
ALTER TABLE BUG ADD CONSTRAINT FK_BUG_ISSUE_ID FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID);
ALTER TABLE STORY ADD CONSTRAINT FK_STORY_ISSUE_ID FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);